### ISSUE TITLE
Yet TODO...

### ISSUE THREAD

**Issue by terentz** [terentz/digit-placing-puzzle#1]
- [x] Create SVG board
- [ ] Add controls.
- [ ] Create layout - holy grail liquid...
- [x] Create game play functionality.
- [ ] Create invalid node notification.
- [x] Create restart functionality.
- [ ] Create solution functionality.
